---
- name: Get Root Certificate From Address
  shell: "openssl s_client -showcerts -connect {{ root_cert_address }} </dev/null 2>/dev/null | openssl x509 -outform PEM"
  register: root_cert_content

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: red_hat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: darwin.yml
  when: ansible_os_family == "Darwin"
