---
- name: Make sure the folder exists (Red Hat)
  file:
    path: /etc/pki/ca-trust/source/anchors
    state: directory

- name: Copy PEM into folder (Red Hat)
  copy:
    content: "{{ root_cert_content }}"
    dest: "/etc/pki/ca-trust/source/anchors/{{ root_cert_address }}"
  register: result

- name: Update CA Trust (Red Hat)
  command: update-ca-trust
  when: result is changed

- name: Update CA Trust (Red Hat < 7)
  command: update-ca-trust enable
  when:
    - result is changed
    - ansible_distribution_version|int < 7
